config/routes.rb
BrowserGame::Application.routes.draw do

  resources :players do
    resources :gold, :only => [:update]
  end

  devise_for :users, :path => "usuarios", :path_names => { :sign_out => "sair", :sign_in => "entrar", :sign_up => "registrar", :password => "senha" }

  match "free" => "home#free"
  root :to => 'home#index'

end

app/models/player.rb
class Player < ActiveRecord::Base
  attr_accessible :nickname, :race_id
  belongs_to :race
  belongs_to :user
  
  
  validates :nickname, :presence => true
  
  def change_gold!(value)
    if there_is_a_buy_of_gold_from_the_user_for?(value)
      self.gold += value
    end
    save
  end
  
  private
  
  def there_is_a_buy_of_gold_from_the_user_for?(value)
    true
  end
end

app/models/race.rb
class Race < ActiveRecord::Base
  attr_accessible :name
  has_many :players
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_many :players
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
end

app/controllers/gold_controller.rb
# encoding: utf-8
class GoldController < ApplicationController
  def update
    player = current_user.players.find(params[:player_id])
    
    
    if player.change_gold!(params[:id].to_i)
      redirect_to :back, :notice => "Voc‪e esta agora com #{player.gold} gold"
      else
      redirect_to :back, :error => "nao foi possivel alterar seu gold"
      end
    
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :authenticate_user!, :only => [:free]
  
  def free
  end

  def index
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  
  def index
    @players = current_user.players
  end
  
  def show
    @player = current_user.players.find(params[:id])
  end

  def new
    @player = current_user.players.build

  end

  def edit
    @player = current_user.players.find(params[:id])
  end

  def create
    @player = current_user.players.build(params[:player])

      if @player.save
        redirect_to @player, notice: 'Player was successfully created.'
      else
        render action: "new"
      end
  end

  def update
    @player = current_user.players.find(params[:id])

      if @player.update_attributes(params[:player])
        redirect_to @player, notice: 'Player was successfully updated.'
      else
        render action: "edit"
      end
  end

  def destroy
    @player = current_user.players.find(params[:id])
    @player.destroy


    redirect_to players_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gold_helper.rb
module GoldHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/gold/update.html.erb
<h1>Gold#update</h1>
<p>Find me in app/views/gold/update.html.erb</p>

app/views/home/free.html.erb
Im free!!!!

<% if user_signed_in? %>
Logado como <%= current_user.email %>
<% else %>
Deslogado
<% end %>

app/views/home/index.html.erb
<%= link_to "Sair", destroy_user_session_path %>

Ola

<%= link_to "Cadastre-se", new_user_registration_path %>
ou

<%= link_to "Entrar", new_user_session_path %>

<%= link_to "Personagens", players_path %>
<% unless current_user.players.empty? %>
  <%= link_to "Personagem Principal", player_path(current_user.players.first) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BrowserGame</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nickname %><br />
    <%= f.text_field :nickname %>
  </div>
  <div class="field">
    <%= f.label :race %><br />
    <%= f.collection_select :race_id, Race.all, :id, :name, :prompt => true %>
  </div>
  <%= f.text_field :gold %>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<h1>Listing players</h1>

<table>
  <tr>
    <th>Nickname</th>
    <th>Gold</th>
    <th>Score</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @players.each do |player| %>
  <tr>
    <td><%= player.nickname %></td>
    <td><%= player.gold %></td>
    <td><%= player.score %></td>
    <td><%= link_to 'Show', player %></td>
    <td><%= link_to 'Edit', edit_player_path(player) %></td>
    <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<h1>New player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p>
  <b>Nickname:</b>
  <%= @player.nickname %>
</p>

<p>
  <b>Gold:</b>
  <%= @player.gold %>
</p>

<p>
  <b>Score:</b>
  <%= @player.score %>
</p>

<%= link_to 'Dar 10 Gold', player_gold_path(@player, 10), :method => :put %>
<%= link_to 'tirar 10 Gold', player_gold_path(@player, -10), :method => :put %>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>